# Generated by Django 4.2.4 on 2023-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='datetime_job_resume',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время возобновления работы'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='job_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность работы'),
        ),
    ]
