# Generated by Django 4.2.4 on 2023-11-08 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_shifttask_datetime_job_resume_shifttask_job_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttask',
            options={'verbose_name': 'Сменное задание', 'verbose_name_plural': 'Сменные задания'},
        ),
        migrations.AddField(
            model_name='shifttask',
            name='next_shift_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_shift_task', to='scheduler.shifttask', verbose_name='Новое СЗ на исправление брака'),
        ),
    ]
